#数据库配置
DatabaseSettings:
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "MHDF-Bot"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#登录系统数据库配置
LoginSystemDatabaseSettings:
  #MHDF登录插件
  isMHDFLogin: true
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "mhdflogin"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#ChengBot设置
ChengBotSettings:
  #API地址
  APIUrl: "http://127.0.0.1:5678"
  #菜单URI
  Menu: "/getImage/Menu"
  #系统状态URI
  SystemInfo: "/getImage/SystemInfo"
  #服务器信息URI
  ServerInfo: "/getImage/ServerInfo?Server=W3sibmFtZSI6IuaipuWbnuS4nOaWuSIsImlwIjoibWhkZi5sb3ZlIn1d"

#群老婆系统开关
MarryEnable: true

#允许使用管理命令的QQ
AllowUseAdminCommandList:
  - "2624246773"
  - "292200693"

#允许使用QQ机器人的群聊
AllowUseBotList:
  - "476308572"
  - "958871704"

#回复消息@
ReplayAt: true

#批量踢出设置
KickSettings:
  #获取QQ等级最大重试次数
  GetQQLevelMaxTryTimes: 5

#绑定设置
BindSettings:
  #单个QQ最多可以绑定的用户数量
  MaxBind: 1
  #绑定QQ最低QQ等级要求
  MinQQLevel: 10

#群聊屏蔽词设置
BlackWordSettings:
  #开关
  Enable: true
  #启动sensitive-word库检测屏蔽词（https://github.com/houbb/sensitive-word）
  EnableSensitiveWordAPI: false
  #禁言(单位：分钟 设置 -1关闭)
  Mute: 10
  #屏蔽词
  BlackWordList:
    - "傻逼"