#数据库配置
DatabaseSettings:
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "MHDF-Bot"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#登录系统数据库配置
LoginSystemDatabaseSettings:
  #MHDF登录插件
  isMHDFLogin: true
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "mhdflogin"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#ChengBot设置
ChengBotSettings:
  #API地址
  APIUrl: "http://127.0.0.1:5678"
  #菜单URI
  Menu: "/getImage/Menu"
  #系统状态URI
  SystemInfo: "/getImage/SystemInfo"
  #服务器信息URI
  ServerInfo: "/getImage/ServerInfo?Server=W3sibmFtZSI6IuaipuWbnuS4nOaWuSIsImlwIjoibWhkZi5sb3ZlIn1d"

#允许使用管理命令的QQ
AllowUseAdminCommandList:
  - "2624246773"
  - "292200693"

#允许使用QQ机器人的群聊
AllowUseBotList:
  - "476308572"
  - "273185916"

#群老婆系统开关
MarryEnable: true

#回复消息@
ReplayAt: true

#聊天系统设置
ChatSettings:
  #开关
  Enable: true
  #获取QQ昵称最大重试次数
  GetQQNameMaxTryTimes: 5
  #QQ昵称映射
  QQToName:
    QQ2624246773: "筱宇"
    QQ292200693: "橙汁"

#批量踢出设置
KickSettings:
  #获取QQ等级最大重试次数
  GetQQLevelMaxTryTimes: 5

#绑定设置
BindSettings:
  #验证玩家开关
  Verify: false
  #允许解除绑定
  AllowUnBind: true
  #单个QQ最多可以绑定的用户数量
  MaxBind: 1
  #绑定QQ最低QQ等级要求
  MinQQLevel: 10
  #绑定ID字符限制
  BindNameRegex: "^[a-zA-Z0-9_]+$"
  #绑定ID最小长度
  BindNameMinLength: 3
  #绑定ID最大长度
  BindNameMaxLength: 16
  #绕过绑定上线的QQ
  BypassMaxBindList:
    - "2624246773"
    - "292200693"

#自动聊天
AutoChat:
  #开关
  Enable: true
  #关键词列表
  WordList:
    #自定义名称
    圈地教程:
      #关键词
      Words:
        - "怎么圈地"
        - "圈地教程"
      Replay: |-
        首先使用小木锄,先这样在那样,最后再那样就可以了!
    憋回去:
      #关键词
      Words:
        - "爽"
      Replay: |-
        主人不可以随便爽哦,请憋回去!
    补偿:
      #关键词
      Words:
        - "补偿"
      Replay: |-
        什么是补偿啊,梦东娘不知道啊!

#群聊屏蔽词设置
BlackWordSettings:
  #开关
  Enable: true
  #启动sensitive-word库检测屏蔽词（https://github.com/houbb/sensitive-word）
  EnableSensitiveWordAPI: false
  #禁言(单位：分钟 设置 -1关闭)
  Mute: 10
  #屏蔽词
  BlackWordList:
    - "傻逼"
    - "习近平"
    - "毒品"
    - "东亚病夫"