#数据库配置
DatabaseSettings:
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "MHDF-Bot"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#登录系统数据库配置
LoginSystemDatabaseSettings:
  #MHDF登录插件
  isMHDFLogin: true
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "mhdflogin"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#允许聊天
AllowChat: true

#允许加入的服务器列表
AllowJoinServerList:
  - "登录大厅"
  - "主城"

#允许使用的命令
AllowUseCommandList:
  - "/l"
  - "/reg"

Messages:
  AntiChat: "&f붃 &c你没有绑定QQ,无法聊天!"
  AntiUseCommand: "&f붃 &c请前往官方QQ群476308572输入#绑定 你的角色ID后再进行操作!"