########################################################################################################
#PAPI变量:
#%MHDFBot_isBind%             是否绑定
#%MHDFBot_getQQ%              获取绑定的QQ
#%MHDFBot_getChatTimes%       获取积累聊天数
#%MHDFBot_getDayChatTimes%    获取今日聊天数
########################################################################################################

#数据库配置
DatabaseSettings:
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "MHDF-Bot"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#登录系统数据库配置
LoginSystemDatabaseSettings:
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库
  Database: "mhdflogin"
  #数据库账户
  Username: "root"
  #数据库密码
  Password: "root"

#机器人WS服务器地址
BotWebSocketServerHost: "ws://127.0.0.1:5888/MHDFBot"

#提示用户绑定账户
SendMessage: true

#绑定完成操作
Actions:
  #绑定完成
  #============================================
  #操作列表
  #[player]|<命令> #玩家执行命令
  #[console]|<命令> #后台执行命令
  #[playsound]|<音频>|<音量|<音效> #播放音频
  #[playsound_pack]|<音频>|<音量|<音效> #播放资源包音频
  #[message]|<消息第一行>|<消息第二行> #发送消息
  #[title]|<消息第一行>|<消息第二行>|淡出时间|停留时间|淡出时间 #发送标题消息
  #[actionbar]|<消息> #发送ActionBar消息
  #============================================
  BindDone:
    - "[playsound]|BLOCK_ANVIL_PLACE|25|1.3"
    - "[title]|&a绑定成功!|&a开始你的游戏吧!|0|25|20"

#音效设置
Sound:
  NoBind: "ENTITY_EXPERIENCE_ORB_PICKUP|25|0.7"
  AtQQ: "ENTITY_EXPERIENCE_ORB_PICKUP|25|0.7"

#语言文件设置
Messages:
  ReloadDone: "&a重载完成!"
  NoBind: "&c请绑定QQ账户!|&a请在QQ群&b476308572&a中发送&b#绑定 <游戏ID>|0|25|20"
  AtQQ: "&a你在&bQQ群&a中被AT了!|&e请前往&bQQ群&e查看|10|70|20"
  Bind: "&a已绑定"
  NotBind: "&c未绑定"